name: codequiz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.5.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.13.1 
  http: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_picker: ^1.0.4
  shared_preferences: ^2.0.12
  supabase_flutter: ^1.10.23
  fluttertoast: ^8.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: GoodDog
      fonts:
        - asset: assets/fonts/gooddog.ttf
  